name: schedule jobs
on:
  cron: "*/5 * * *"
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
      - name: Setup node
        uses: actions/setup-node@v5
      - name: install node js project
        run: npm install